// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package database

import (
	"context"
)

const getRoleByName = `-- name: GetRoleByName :one
SELECT name, hierarchy_level FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.Name, &i.HierarchyLevel)
	return i, err
}
